kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oss
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      alicloud-pvname: oss-ack-pre
